### ISSUE TITLE
Cannot Play mpegts stream

### ISSUE THREAD

**Issue by berkayeren** [4gray/my-iptv-player-pwa#1]
Hi, application is works just fine with hls streams but when the play list is mpegts, video player just shows loading icon and never plays the video. On the other hand, stream seems connected and when i check it from the stream panel, i can see that i am connected to selected stream. Do you have any idea about how to play mpegts stream in the player?

**Comment by 4gray** [comment]
Hi, thank you for the feedback. 
Do you have any sample file or URL with mpegts stream, which I can test?

**Comment by berkayeren** [comment]
Hi, i send mpegts stream url to your email address. Link is up and running right now. If you inspect on the network tab, you will see that stream is connected but player is showing loading icon only.

**Comment by mhos** [comment]
Was there an actual resolve to this? I have the same issues.
Ubuntu 20.04 IPTVnator 0.3.0.
Can see the stream moving in network but player just shows spinning circle.

**Comment by 4gray** [comment]
Unfortunately not. The video player is based on [hls.js](https://github.com/video-dev/hls.js) and it seems like hls.js doesn't support the format from your stream.
See: 
https://github.com/video-dev/hls.js/issues/1794
https://github.com/video-dev/hls.js/issues/2549

Btw there is a demo page, where you can try your stream: https://hls-js.netlify.app/demo/
